spring:
  rabbitmq:
    host: 101.43.56.164
    port: 5672
    #建通自定义虚拟主机
    virtual-host: "/lunfee"
    password: lunfee
    username: lunfee
    template:
      #Cloud Stream 默认使用的 rabbitmq 的 Topic 模式，因此要设置routing_key
      routing-key: laser.*
#Cloud流式编程中，Consumer 自动监听 方法名-in-0, 因此将其与 rabbitmq 对应的 exchange 绑定
#group 定义消费者组，避免匿名队列的产生
#  cloud:
#    stream:
#      bindings:
#        onReceive-in-0:
#          destination: laser-topic
#          group: consumer

server:
  port: 80


hbase:
  config:
    hbase:
      master: 101.43.56.164:16010
      zookeeper:
        property:
          clientPort: 2181
        #连接 zookeeper 不允许使用ip，lunfeehbase 是 hbase Docker 容器的 host， 远程访问时在本地 hosts 配置了 101.43.56.164 lunfeehbase
        quorum: lunfeehbase