server:
  port: 8081

#rabbitma 配置
spring:
  rabbitmq:
    host: 101.43.56.164
    port: 5672
    #建通自定义虚拟主机
    virtual-host: "/lunfee"
    password: lunfee
    username: lunfee
    template:
      #Cloud Stream 默认使用的 rabbitmq 的 Topic 模式，因此要设置routing_key
      routing-key: laser.*