spring:
  rabbitmq:
    host: 101.43.56.164
    port: 5672
  cloud:
    stream:
      bindings:

        convertToUppercase-in-0:
          destination: values-topic
          group: processor

        convertToUppercase-out-0:
          destination: uppercase-values-topic